swagger: '2.0'
info:
  title: FindBranch
  x-ibm-name: findbranch
  version: 2.0.5
schemes:
  - https
basePath: /findbranch
security:
  - clientID: []
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
x-ibm-configuration:
  phase: realized
  testable: true
  enforced: true
  properties:
    target-url:
      value: 'https://apictutorials.mybluemix.net/branches'
      description: The URL of the target service
      encoded: false
  cors:
    enabled: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: ($operationPath() = '/details')
              execute:
                - invoke:
                    title: invoke
                    version: 2.0.0
                    verb: keep
                    target-url: $(target-url)
            - condition: ($operationPath() = '/get')
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error: []
                    target-url: 'https://postman-echo.com/get'
  gateway: datapower-api-gateway
  type: rest
  application-authentication:
    certificate: false
definitions:
  branch:
    type: object
    description: The format of the branch field.
    properties:
      address:
        $ref: '#/definitions/address'
        properties: {}
        description: The address of the branch
      type:
        type: string
        description: The type of branch
        example: atm
      id:
        type: string
        description: The ID of the branch
        example: "\t9d72ece0-7e7b-11e5-9038-55f9f9c08c06"
  address:
    type: object
    properties:
      street1:
        type: string
        description: The first line of the address
        example: 4660 La Jolla Village Drive
      street2:
        type: string
        description: The second line of the address
        example: Suite 300
      city:
        type: string
        description: The city of the address
        example: San Diego
      state:
        type: string
        description: The state of the address
        example: CA
      zip_code:
        type: string
        description: The zip code of the address
        example: '92122'
paths:
  /get:
    get:
      responses:
        '200':
          schema:
            type: string
          description: success
  /details:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/branch'
      parameters: []
